name: OneJS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  UNITY_VERSION: '6000.0.48f1'
  PROJECT_PATH: OneJS_CI_Project
  SAMPLE_SCENE: Assets/OneJS/Samples/OneJS_SampleScene.unity

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Node is needed because the test drives npm/tsc/esbuild
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Create empty project + import OneJS
      - name: Bootstrap minimal Unity project
        run: |
          mkdir -p "$PROJECT_PATH/Assets" "$PROJECT_PATH/Packages" "$PROJECT_PATH/ProjectSettings"
          echo '{}' > "$PROJECT_PATH/Packages/manifest.json"
          echo "m_EditorVersion: $UNITY_VERSION" > "$PROJECT_PATH/ProjectSettings/ProjectVersion.txt"
          rsync -a --exclude=.git --exclude=.github ./ "$PROJECT_PATH/Assets/OneJS"

      # Cache Library for faster reruns
      - uses: actions/cache@v3
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.UNITY_VERSION }}-${{ github.sha }}
          restore-keys: |
            Library-${{ env.UNITY_VERSION }}-

      # Playmode tests
      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          projectPath: ${{ env.PROJECT_PATH }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: playmode

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: artifacts

      # Build the Sample Scene
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          projectPath: ${{ env.PROJECT_PATH }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          targetPlatform: StandaloneLinux64
          buildName: OneJS_Sample
          buildScenes: ${{ env.SAMPLE_SCENE }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
